// Cakna Hub/app/docs/[slug]/page.tsx
import { notFound } from "next/navigation";
import { ArrowLeft, CalendarDays } from "lucide-react";
import Link from "next/link";
import type { Metadata } from "next";
import { getSiteContent } from "@/lib/site-store";
import PublicShell from "@/components/public/PublicShell";

export const dynamic = "force-dynamic";

const VALID_SLUGS = ["policy", "sop", "guidelines", "manual"] as const;
type DocSlug = (typeof VALID_SLUGS)[number];

const LABELS: Record<DocSlug, string> = {
  policy: "Polisi",
  sop: "SOP",
  guidelines: "Garis Panduan",
  manual: "Manual",
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  if (!VALID_SLUGS.includes(slug as DocSlug)) return {};
  const content = await getSiteContent();
  const doc = content.docs[slug as DocSlug];
  return { title: `${doc.title} · Cakna Hub` };
}

export default async function DocPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  if (!VALID_SLUGS.includes(slug as DocSlug)) notFound();

  const content = await getSiteContent();
  const doc = content.docs[slug as DocSlug];
  const paras = doc.content.split(/\n\s*\n/).map((p) => p.trim()).filter(Boolean);

  return (
    <PublicShell content={content}>
      {/* Hero */}
      <section className="bg-gradient-to-b from-rose-50 to-white py-16">
        <div className="mx-auto max-w-4xl px-6">
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-sm font-medium text-zinc-500 hover:text-rose-700"
          >
            <ArrowLeft size={15} />
            Kembali
          </Link>
          <div className="mt-4 inline-flex items-center gap-1.5 rounded-full bg-rose-100 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-rose-700">
            {LABELS[slug as DocSlug]}
          </div>
          <h1 className="mt-3 text-4xl font-bold tracking-tight text-zinc-900 sm:text-5xl">
            {doc.title}
          </h1>
          {doc.subtitle && (
            <p className="mt-4 text-lg text-zinc-600">{doc.subtitle}</p>
          )}
          {doc.lastUpdated && (
            <p className="mt-4 inline-flex items-center gap-1.5 text-sm text-zinc-400">
              <CalendarDays size={14} />
              Dikemaskini: {doc.lastUpdated}
            </p>
          )}
        </div>
      </section>

      {/* Content */}
      <article className="mx-auto max-w-4xl px-6 py-12">
        <div className="prose prose-zinc max-w-none">
          {paras.map((p, i) => (
            <p key={i} className="mt-4 leading-relaxed text-zinc-700 first:mt-0">
              {p}
            </p>
          ))}
        </div>

        <div className="mt-16 border-t border-zinc-100 pt-8">
          <p className="text-sm text-zinc-400">
            Untuk pertanyaan lanjut, sila hubungi pasukan HOME CAKNA.
          </p>
          <div className="mt-4 flex flex-wrap gap-3">
            {VALID_SLUGS.filter((s) => s !== slug).map((s) => (
              <Link
                key={s}
                href={`/docs/${s}`}
                className="rounded-lg border border-zinc-200 bg-white px-4 py-2 text-sm font-medium text-zinc-600 transition-colors hover:border-rose-200 hover:text-rose-700"
              >
                {LABELS[s]}
              </Link>
            ))}
          </div>
        </div>
      </article>
    </PublicShell>
  );
}

// Cakna Hub/src/routes/docs/[slug]/+page.svelte
<script lang="ts">
	import PublicShell from '$lib/components/public/PublicShell.svelte';
	import { ArrowLeft, BookOpen } from 'lucide-svelte';
	let { data } = $props();
	const { slug, doc, content } = $derived(data);

	const slugLabels: Record<string, string> = {
		policy: 'Polisi',
		sop: 'SOP',
		guidelines: 'Garis Panduan',
		manual: 'Manual'
	};
	const label = slugLabels[slug] ?? slug;
</script>
<svelte:head><title>{doc?.title ?? label} · {content.brand.name}</title></svelte:head>
<PublicShell {content}>
	<main class="mx-auto max-w-3xl px-6 py-16">
		<a href="/" class="inline-flex items-center gap-1.5 text-sm text-zinc-500 hover:text-zinc-900">
			<ArrowLeft size={16} /> Laman Utama
		</a>

		{#if doc}
			<div class="mt-8 flex items-start gap-4">
				<span class="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-rose-50 text-rose-600">
					<BookOpen size={20} />
				</span>
				<div>
					<h1 class="text-3xl font-bold tracking-tight text-zinc-900">{doc.title}</h1>
					{#if doc.subtitle}
						<p class="mt-1.5 text-base text-zinc-500">{doc.subtitle}</p>
					{/if}
				</div>
			</div>

			{#if doc.content}
				<div class="mt-8 space-y-4">
					{#each doc.content.split(/\n\s*\n/).filter(Boolean) as p}
						<p class="leading-relaxed text-zinc-700">{p}</p>
					{/each}
				</div>
			{:else}
				<p class="mt-8 text-zinc-500">Kandungan dokumen ini sedang disediakan.</p>
			{/if}

			{#if doc.lastUpdated}
				<p class="mt-10 text-sm text-zinc-400">Dikemaskini: {doc.lastUpdated}</p>
			{/if}
		{:else}
			<div class="mt-8 flex items-start gap-4">
				<span class="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-rose-50 text-rose-600">
					<BookOpen size={20} />
				</span>
				<div>
					<h1 class="text-3xl font-bold tracking-tight text-zinc-900">{label}</h1>
					<p class="mt-1.5 text-zinc-500">Kandungan dokumen ini sedang disediakan oleh admin.</p>
				</div>
			</div>
		{/if}
	</main>
</PublicShell>
