// Cakna Hub/src/lib/components/society/StatusBadge.svelte
<script lang="ts">
	import { statusLabel } from '$lib/types';

	let { status }: { status: string } = $props();

	const colors: Record<string, string> = {
		pending_dept: 'bg-amber-50 text-amber-700 ring-amber-200',
		pending_cakna: 'bg-blue-50 text-blue-700 ring-blue-200',
		approved: 'bg-emerald-50 text-emerald-700 ring-emerald-200',
		needs_revision: 'bg-red-50 text-red-700 ring-red-200',
		pending: 'bg-amber-50 text-amber-700 ring-amber-200'
	};

	const cls = $derived(colors[status] ?? 'bg-zinc-50 text-zinc-700 ring-zinc-200');
</script>

<span class="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ring-1 ring-inset {cls}">
	{statusLabel(status)}
</span>

// Cakna Hub/components/society/StatusBadge.tsx
import { statusLabel } from "@/lib/society";

// Semantic status colors — kept distinct from the pink brand accent.
const styles: Record<string, string> = {
  pending: "bg-amber-50 text-amber-700", // legacy alias
  pending_dept: "bg-amber-50 text-amber-700",
  pending_cakna: "bg-indigo-50 text-indigo-700",
  approved: "bg-emerald-50 text-emerald-700",
  needs_revision: "bg-rose-50 text-rose-700",
};

export default function StatusBadge({ status }: { status: string }) {
  const cls = styles[status] ?? "bg-zinc-100 text-zinc-600";
  return (
    <span
      className={`inline-block whitespace-nowrap rounded-md px-2 py-0.5 text-xs font-medium ${cls}`}
    >
      {statusLabel(status)}
    </span>
  );
}
