// Cakna Hub/src/routes/hub/admin/site/docs/[slug]/+page.svelte
<script lang="ts">
	import { ArrowLeft } from 'lucide-svelte';

	let { data, form } = $props();

	const slugLabels: Record<string, string> = {
		policy: 'Polisi',
		sop: 'SOP',
		guidelines: 'Garis Panduan',
		manual: 'Manual'
	};

	let title = $state(data.doc?.title ?? '');
	let subtitle = $state(data.doc?.subtitle ?? '');
	let content = $state(data.doc?.content ?? '');
	let lastUpdated = $state(data.doc?.lastUpdated ?? '');

	const label = slugLabels[data.slug] ?? data.slug;

	const inp =
		'rounded-lg border border-zinc-300 px-3 py-2 text-sm focus:border-rose-400 focus:outline-none focus:ring-2 focus:ring-rose-100 w-full bg-white';
	const ta = inp + ' resize-y';
	const lbl = 'text-sm font-medium text-zinc-700';
</script>

<svelte:head><title>{label} · Dokumen · Cakna Hub Admin</title></svelte:head>

<div class="space-y-6 pb-16">
	<div class="flex items-center gap-3">
		<a
			href="/hub/admin/site/docs"
			class="inline-flex items-center gap-1.5 text-sm text-zinc-500 hover:text-zinc-900"
		>
			<ArrowLeft size={16} /> Dokumen
		</a>
		<span class="text-zinc-300">/</span>
		<h1 class="text-xl font-bold text-zinc-900">{label}</h1>
	</div>

	{#if form?.error}
		<div class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
			{form.error}
		</div>
	{/if}

	<form method="POST" class="space-y-5">
		<div class="space-y-5 rounded-2xl border border-zinc-200 bg-white p-6">
			<label class="flex flex-col gap-1.5">
				<span class={lbl}>Tajuk</span>
				<input name="title" bind:value={title} class={inp} placeholder="Polisi" required />
			</label>

			<label class="flex flex-col gap-1.5">
				<span class={lbl}>
					Subtajuk
					<span class="font-normal text-zinc-400">(optional)</span>
				</span>
				<input
					name="subtitle"
					bind:value={subtitle}
					class={inp}
					placeholder="Dasar dan polisi rasmi…"
				/>
			</label>

			<label class="flex flex-col gap-1.5">
				<span class={lbl}>
					Kandungan
					<span class="font-normal text-zinc-400">(perenggan dipisah dengan baris kosong)</span>
				</span>
				<textarea
					name="content"
					bind:value={content}
					rows={12}
					class={ta}
					placeholder="Tulis kandungan dokumen di sini…"
				></textarea>
			</label>

			<label class="flex flex-col gap-1.5">
				<span class={lbl}>Dikemaskini</span>
				<input name="lastUpdated" bind:value={lastUpdated} class={inp} placeholder="2026" />
			</label>
		</div>

		<div class="flex items-center justify-between">
			<a href="/hub/admin/site/docs" class="text-sm text-zinc-500 hover:text-zinc-900">
				← Batal
			</a>
			<button
				type="submit"
				class="rounded-xl bg-rose-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-rose-700"
			>
				Simpan perubahan
			</button>
		</div>
	</form>
</div>

// Cakna Hub/app/docs/[slug]/page.tsx
import { notFound } from "next/navigation";
import { ArrowLeft, CalendarDays } from "lucide-react";
import Link from "next/link";
import type { Metadata } from "next";
import { getSiteContent } from "@/lib/site-store";
import PublicShell from "@/components/public/PublicShell";

export const dynamic = "force-dynamic";

const VALID_SLUGS = ["policy", "sop", "guidelines", "manual"] as const;
type DocSlug = (typeof VALID_SLUGS)[number];

const LABELS: Record<DocSlug, string> = {
  policy: "Polisi",
  sop: "SOP",
  guidelines: "Garis Panduan",
  manual: "Manual",
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  if (!VALID_SLUGS.includes(slug as DocSlug)) return {};
  const content = await getSiteContent();
  const doc = content.docs[slug as DocSlug];
  return { title: `${doc.title} · Cakna Hub` };
}

export default async function DocPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  if (!VALID_SLUGS.includes(slug as DocSlug)) notFound();

  const content = await getSiteContent();
  const doc = content.docs[slug as DocSlug];
  const paras = doc.content.split(/\n\s*\n/).map((p) => p.trim()).filter(Boolean);

  return (
    <PublicShell content={content}>
      {/* Hero */}
      <section className="bg-gradient-to-b from-rose-50 to-white py-16">
        <div className="mx-auto max-w-4xl px-6">
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-sm font-medium text-zinc-500 hover:text-rose-700"
          >
            <ArrowLeft size={15} />
            Kembali
          </Link>
          <div className="mt-4 inline-flex items-center gap-1.5 rounded-full bg-rose-100 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-rose-700">
            {LABELS[slug as DocSlug]}
          </div>
          <h1 className="mt-3 text-4xl font-bold tracking-tight text-zinc-900 sm:text-5xl">
            {doc.title}
          </h1>
          {doc.subtitle && (
            <p className="mt-4 text-lg text-zinc-600">{doc.subtitle}</p>
          )}
          {doc.lastUpdated && (
            <p className="mt-4 inline-flex items-center gap-1.5 text-sm text-zinc-400">
              <CalendarDays size={14} />
              Dikemaskini: {doc.lastUpdated}
            </p>
          )}
        </div>
      </section>

      {/* Content */}
      <article className="mx-auto max-w-4xl px-6 py-12">
        <div className="prose prose-zinc max-w-none">
          {paras.map((p, i) => (
            <p key={i} className="mt-4 leading-relaxed text-zinc-700 first:mt-0">
              {p}
            </p>
          ))}
        </div>

        <div className="mt-16 border-t border-zinc-100 pt-8">
          <p className="text-sm text-zinc-400">
            Untuk pertanyaan lanjut, sila hubungi pasukan HOME CAKNA.
          </p>
          <div className="mt-4 flex flex-wrap gap-3">
            {VALID_SLUGS.filter((s) => s !== slug).map((s) => (
              <Link
                key={s}
                href={`/docs/${s}`}
                className="rounded-lg border border-zinc-200 bg-white px-4 py-2 text-sm font-medium text-zinc-600 transition-colors hover:border-rose-200 hover:text-rose-700"
              >
                {LABELS[s]}
              </Link>
            ))}
          </div>
        </div>
      </article>
    </PublicShell>
  );
}
