// Cakna Hub/src/lib/components/admin/AdminShell.svelte
<script lang="ts">
	import AdminSidebar from './AdminSidebar.svelte';
	import type { HubUser } from '$lib/types';

	interface Props {
		user: HubUser;
		contentClassName?: string;
		children: import('svelte').Snippet;
	}
	let { user, contentClassName = 'mx-auto max-w-5xl px-6 py-8 md:py-10', children }: Props = $props();
</script>

<div class="min-h-screen bg-zinc-50/40 md:flex">
	<AdminSidebar {user} />
	<main class="flex-1 min-w-0">
		<div class={contentClassName}>
			{@render children()}
		</div>
	</main>
</div>

// Cakna Hub/components/admin/AdminShell.tsx
import AdminSidebar from "@/components/admin/AdminSidebar";
import { type PublicUser } from "@/lib/roles";

/**
 * The admin sidebar + content shell. Used by the /admin layout, and by other
 * staff-facing pages (e.g. /notifications) so the sidebar navigation stays
 * consistent even outside the /admin route tree.
 */
export default function AdminShell({
  user,
  children,
  contentClassName = "mx-auto max-w-5xl px-6 py-8 md:py-10",
}: {
  user: PublicUser;
  children: React.ReactNode;
  contentClassName?: string;
}) {
  return (
    <div className="min-h-screen md:flex">
      <AdminSidebar user={user} />
      <main className="flex-1">
        <div className={contentClassName}>{children}</div>
      </main>
    </div>
  );
}
