// Cakna Hub/src/routes/society/funding/+page.svelte
<script lang="ts">
	import { Plus, ArrowLeft } from 'lucide-svelte';
	import StatusBadge from '$lib/components/society/StatusBadge.svelte';
	import { formatRM } from '$lib/format';

	let { data } = $props();
	const { applications } = $derived(data);
</script>

<svelte:head><title>Funding Applications · Cakna Hub</title></svelte:head>

<main class="mx-auto max-w-4xl px-6 py-12">
	<a href="/" class="inline-flex items-center gap-1.5 text-sm text-zinc-500 transition-colors hover:text-zinc-900">
		<ArrowLeft size={16} /> Home
	</a>

	<div class="mt-6 flex flex-wrap items-start justify-between gap-4">
		<div>
			<h1 class="text-2xl font-bold tracking-tight text-zinc-900">Funding Applications</h1>
			<p class="mt-1.5 text-zinc-500">Events and programmes submitted for funding.</p>
		</div>
		<a href="/society/funding/new" class="inline-flex items-center gap-2 rounded-xl bg-rose-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-rose-700">
			<Plus size={16} /> New Application
		</a>
	</div>

	{#if applications.length === 0}
		<div class="mt-16 text-center text-zinc-400">
			<p class="text-lg font-medium">No applications yet.</p>
			<p class="mt-1 text-sm">Submit the first one using the button above.</p>
		</div>
	{:else}
		<ul class="mt-8 divide-y divide-zinc-100 rounded-2xl border border-zinc-200 bg-white">
			{#each applications as a (a.id)}
				<li>
					<a href="/society/funding/{a.id}" class="flex flex-wrap items-center justify-between gap-3 px-5 py-4 transition-colors hover:bg-zinc-50">
						<div class="min-w-0">
							<p class="truncate text-sm font-semibold text-zinc-900">{a.namaProgram}</p>
							<p class="mt-0.5 text-xs text-zinc-400">{a.reference} · {a.cawangan}</p>
						</div>
						<div class="flex shrink-0 items-center gap-3">
							<StatusBadge status={a.status} />
							<span class="text-sm font-medium tabular-nums text-zinc-700">{formatRM(a.jumlahPerbelanjaan)}</span>
						</div>
					</a>
				</li>
			{/each}
		</ul>
	{/if}
</main>

// Cakna Hub/app/admin/funding/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, FileText, Download } from "lucide-react";
import StatCard from "@/components/admin/StatCard";
import AmountBars from "@/components/admin/AmountBars";
import FundingApplicationsList from "@/components/admin/FundingApplicationsList";
import { getFundingApplications } from "@/lib/society-store";
import { getCurrentUser } from "@/lib/auth";
import { normalizeStatus } from "@/lib/society";
import { fundingByCluster } from "@/lib/reports";
import { formatRM } from "@/lib/format";

export const metadata: Metadata = {
  title: "Funding · Cakna Hub Admin",
};

export const dynamic = "force-dynamic";

export default async function FundingAdminPage() {
  const [applications, user] = await Promise.all([
    getFundingApplications(),
    getCurrentUser(),
  ]);
  const approved = applications.filter(
    (a) => normalizeStatus(a.status) === "approved",
  );
  const pending = applications.filter((a) => {
    const s = normalizeStatus(a.status);
    return s === "pending_dept" || s === "pending_cakna";
  }).length;

  const disbursed = approved.reduce((s, a) => s + a.jumlahPerbelanjaan, 0);
  const clusters = fundingByCluster(approved);

  return (
    <div className="space-y-8">
      <header>
        <h1 className="text-2xl font-bold tracking-tight text-zinc-900">
          Funding
        </h1>
        <p className="mt-1.5 text-zinc-500">
          Review funding applications from Society &amp; Others. Only approved
          applications count as disbursed.
        </p>
        <div className="mt-4 flex flex-wrap gap-2">
          <Link
            href="/admin/funding/report"
            className="inline-flex items-center gap-1.5 rounded-lg border border-zinc-300 bg-white px-3 py-1.5 text-sm font-medium text-zinc-700 transition-colors hover:border-rose-300 hover:text-rose-700"
          >
            <FileText size={15} />
            Consolidated Report (PDF)
          </Link>
          <a
            href="/api/funding/export"
            className="inline-flex items-center gap-1.5 rounded-lg border border-zinc-300 bg-white px-3 py-1.5 text-sm font-medium text-zinc-700 transition-colors hover:border-rose-300 hover:text-rose-700"
          >
            <Download size={15} />
            Download Excel (CSV)
          </a>
        </div>
      </header>

      <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <StatCard
          label="Applications"
          value={String(applications.length)}
          hint="Total submitted"
        />
        <StatCard
          label="Approved"
          value={String(approved.length)}
          hint="Reviewed & approved"
          dot="emerald"
        />
        <StatCard
          label="Pending Review"
          value={String(pending)}
          hint="Awaiting Dept / CAKNA"
          dot="amber"
        />
        <StatCard
          label="Total Disbursed"
          value={formatRM(disbursed)}
          hint="Approved only"
          dot="emerald"
        />
      </section>

      <section className="rounded-2xl border border-zinc-200 bg-white p-6">
        <div className="mb-6">
          <h2 className="text-base font-semibold text-zinc-900">
            Disbursement by core
          </h2>
          <p className="mt-0.5 text-sm text-zinc-500">
            Approved funding disbursed per core.
          </p>
        </div>
        <AmountBars
          rows={clusters.map((c) => ({
            label: c.label,
            value: c.total,
            meta: `${c.count} approved`,
          }))}
        />
      </section>

      <section className="rounded-2xl border border-zinc-200 bg-white p-6">
        <div className="mb-5 flex flex-wrap items-start justify-between gap-3">
          <div>
            <h2 className="text-base font-semibold text-zinc-900">
              Applications &amp; review
            </h2>
            <p className="mt-0.5 text-sm text-zinc-500">
              Approve or request improvements. Most recent first.
            </p>
          </div>
          <Link
            href="/society/funding"
            className="inline-flex items-center gap-1 text-sm font-medium text-rose-600 transition-colors hover:text-rose-700"
          >
            View in Society &amp; Others
            <ArrowUpRight size={14} />
          </Link>
        </div>

        <FundingApplicationsList
          applications={applications}
          role={user?.role ?? "reviewer"}
        />
      </section>
    </div>
  );
}
