// Cakna Hub/src/routes/society/events/new/+page.svelte
<script lang="ts">
	import { ArrowLeft } from 'lucide-svelte';
	import { cores } from '$lib/cores';
	let { data, form } = $props();
</script>
<svelte:head><title>New Event · Cakna Hub</title></svelte:head>
<main class="mx-auto max-w-2xl px-6 py-12">
	<a href="/society/events" class="inline-flex items-center gap-1.5 text-sm text-zinc-500 hover:text-zinc-900"><ArrowLeft size={16} /> Back</a>
	<h1 class="mt-6 text-2xl font-bold tracking-tight text-zinc-900">New Event</h1>
	{#if form?.error}
		<div class="mt-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{form.error}</div>
	{/if}
	<form method="POST" class="mt-8 space-y-5">
		<div class="grid gap-5 sm:grid-cols-2">
			<label class="flex flex-col gap-1.5">
				<span class="text-sm font-medium text-zinc-700">Tajuk Event <span class="text-rose-500">*</span></span>
				<input name="title" required class="rounded-lg border border-zinc-300 px-3.5 py-2.5 text-sm focus:border-rose-400 focus:outline-none focus:ring-2 focus:ring-rose-100" />
			</label>
			<label class="flex flex-col gap-1.5">
				<span class="text-sm font-medium text-zinc-700">Tarikh <span class="text-rose-500">*</span></span>
				<input name="tarikh" type="date" required class="rounded-lg border border-zinc-300 px-3.5 py-2.5 text-sm focus:border-rose-400 focus:outline-none focus:ring-2 focus:ring-rose-100" />
			</label>
		</div>
		<div class="grid gap-5 sm:grid-cols-2">
			<label class="flex flex-col gap-1.5">
				<span class="text-sm font-medium text-zinc-700">Kluster <span class="text-rose-500">*</span></span>
				<select name="kluster" required class="rounded-lg border border-zinc-300 px-3.5 py-2.5 text-sm focus:border-rose-400 focus:outline-none focus:ring-2 focus:ring-rose-100">
					<option value="">Pilih kluster…</option>
					{#each cores as c (c.id)}<option value={c.id}>{c.name}</option>{/each}
				</select>
			</label>
			<label class="flex flex-col gap-1.5">
				<span class="text-sm font-medium text-zinc-700">Lokasi</span>
				<input name="lokasi" class="rounded-lg border border-zinc-300 px-3.5 py-2.5 text-sm focus:border-rose-400 focus:outline-none focus:ring-2 focus:ring-rose-100" />
			</label>
		</div>
		<label class="flex flex-col gap-1.5">
			<span class="text-sm font-medium text-zinc-700">Anjuran</span>
			<input name="anjuran" class="rounded-lg border border-zinc-300 px-3.5 py-2.5 text-sm focus:border-rose-400 focus:outline-none focus:ring-2 focus:ring-rose-100" />
		</label>
		<label class="flex flex-col gap-1.5">
			<span class="text-sm font-medium text-zinc-700">Penerangan</span>
			<textarea name="penerangan" rows="3" class="rounded-lg border border-zinc-300 px-3.5 py-2.5 text-sm focus:border-rose-400 focus:outline-none focus:ring-2 focus:ring-rose-100 resize-none"></textarea>
		</label>
		<div class="flex justify-end gap-3 pt-2">
			<a href="/society/events" class="rounded-lg border border-zinc-300 px-4 py-2.5 text-sm font-medium text-zinc-700 hover:bg-zinc-50">Batal</a>
			<button type="submit" class="rounded-lg bg-rose-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-rose-700">Simpan Event</button>
		</div>
	</form>
</main>

// Cakna Hub/app/society/funding/new/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import SiteHeader from "@/components/SiteHeader";
import FundingForm from "@/components/society/FundingForm";

export const metadata: Metadata = {
  title: "New Funding Application · Cakna Hub",
};

export default function NewFundingPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-12">
      <SiteHeader showBack />

      <Link
        href="/society/funding"
        className="inline-flex items-center gap-1.5 text-sm text-zinc-500 transition-colors hover:text-zinc-900"
      >
        <ArrowLeft size={16} />
        Funding Applications
      </Link>

      <div className="mt-6">
        <h1 className="text-2xl font-bold tracking-tight text-zinc-900">
          Cakna Hub Programme Report
        </h1>
        <p className="mt-1.5 text-zinc-500">
          Program funding application. Please complete the information below.
        </p>
      </div>

      <div className="mt-8">
        <FundingForm />
      </div>
    </main>
  );
}
