// Cakna Hub/src/routes/hub/admin/site/+page.svelte
<script lang="ts">
	import { Home, Info, GraduationCap, Newspaper, Phone, BookOpen } from 'lucide-svelte';

	const pages = [
		{
			href: '/hub/admin/site/home',
			label: 'Home Page',
			desc: 'Hero, about, programs, impact & CTA.',
			icon: Home
		},
		{
			href: '/hub/admin/site/aboutPage',
			label: 'About Us',
			desc: 'Who we are, purpose, collaboration & stats.',
			icon: Info
		},
		{
			href: '/hub/admin/site/setemPage',
			label: 'SETEM',
			desc: 'Math therapy seminar page.',
			icon: GraduationCap
		},
		{
			href: '/hub/admin/site/csrPage',
			label: 'CSR Stories',
			desc: 'Franchisee CSR stories & gallery.',
			icon: Newspaper
		},
		{
			href: '/hub/admin/site/footer',
			label: 'Contact & Footer',
			desc: 'Footer contact details.',
			icon: Phone
		},
		{
			href: '/hub/admin/site/docs',
			label: 'Polisi, SOP & Panduan',
			desc: 'Policy, SOP, guidelines & manual pages.',
			icon: BookOpen
		}
	];
</script>

<svelte:head><title>Website · Cakna Hub Admin</title></svelte:head>

<div class="space-y-8">
	<header>
		<h1 class="text-2xl font-bold tracking-tight text-zinc-900">Website</h1>
		<p class="mt-1.5 text-zinc-500">Edit the public-facing pages by section.</p>
	</header>

	<div class="grid gap-4 sm:grid-cols-2">
		{#each pages as p (p.href)}
			<a
				href={p.href}
				class="group flex items-start gap-4 rounded-2xl border border-zinc-200 bg-white p-5 transition-colors hover:border-rose-200 hover:bg-rose-50"
			>
				<div class="mt-0.5 flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-rose-50 text-rose-600 group-hover:bg-rose-100">
					<svelte:component this={p.icon} size={20} />
				</div>
				<div>
					<p class="font-semibold text-zinc-900">{p.label}</p>
					<p class="mt-0.5 text-sm text-zinc-500">{p.desc}</p>
				</div>
			</a>
		{/each}
	</div>
</div>

// Cakna Hub/app/admin/site/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import {
  BookOpen,
  ChevronRight,
  GraduationCap,
  Home,
  Info,
  Newspaper,
  Phone,
} from "lucide-react";
import { requireRole } from "@/lib/auth";

export const metadata: Metadata = {
  title: "Website · Cakna Hub Admin",
};

export const dynamic = "force-dynamic";

const sections = [
  {
    key: "home",
    title: "Home Page",
    desc: "Hero, about, programs, impact & CTA.",
    Icon: Home,
  },
  {
    key: "about",
    title: "About Us",
    desc: "Who we are, purpose, collaboration & stats.",
    Icon: Info,
  },
  {
    key: "setem",
    title: "SETEM",
    desc: "Math therapy seminar page.",
    Icon: GraduationCap,
  },
  {
    key: "csr",
    title: "CSR Stories",
    desc: "Franchisee CSR stories.",
    Icon: Newspaper,
  },
  {
    key: "contact",
    title: "Contact & Footer",
    desc: "Footer contact details.",
    Icon: Phone,
  },
  {
    key: "docs",
    title: "Polisi, SOP & Panduan",
    desc: "Policy, SOP, guidelines & manual pages.",
    Icon: BookOpen,
  },
];

export default async function SiteHubPage() {
  await requireRole(["admin"], "/admin/site");

  return (
    <div className="space-y-8">
      <header>
        <h1 className="text-2xl font-bold tracking-tight text-zinc-900">
          Website
        </h1>
        <p className="mt-1.5 text-zinc-500">
          Edit the public website — pick a section to edit.
        </p>
      </header>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {sections.map(({ key, title, desc, Icon }) => (
          <Link
            key={key}
            href={`/admin/site/${key}`}
            className="group relative rounded-2xl border border-zinc-200 bg-white p-5 transition-all hover:-translate-y-0.5 hover:border-rose-200 hover:shadow-sm"
          >
            <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-rose-50 text-rose-600">
              <Icon size={20} />
            </div>
            <h2 className="mt-4 font-semibold text-zinc-900">{title}</h2>
            <p className="mt-1 text-sm text-zinc-500">{desc}</p>
            <ChevronRight
              size={18}
              className="absolute right-5 top-5 text-zinc-300 transition-colors group-hover:text-rose-400"
            />
          </Link>
        ))}
      </div>
    </div>
  );
}
